### ISSUE TITLE
能不能放一个release啊

### ISSUE THREAD

**Issue by lc-company** [TZG-official/Jvav-Windows#1]

**Comment by TheZihanGu** [comment]
这边目前这个项目是@APJifengc 在写...还没有写完的样子。
有Release将会在Jvav.top和这个存储库Release.

**Comment by APJifengc** [comment]
在写了在写了 不要着急

**Comment by lc-company** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "APJifengc"<notifications@github.com&gt;; 
发送时间: 2020年4月24日(星期五) 下午5:40
收件人: "TZG-official/Jvav-Windows"<Jvav-Windows@noreply.github.com&gt;; 
抄送: "2678459839"<2678459839@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [TZG-official/Jvav-Windows] 能不能放一个release啊 (#1)





 
在写了在写了 不要着急
