### ISSUE TITLE
👴下载jvav报毒

### ISSUE THREAD

**Issue by baohong-cn228813509** [TZG-official/Jvav-Windows#3]
正规编程语言怎么能被360/McAfee等杀毒软件报毒呢？说好的学习jvav不就业，全额赔么？给👴爪巴。【手动狗头】

**Comment by 30266-Official** [comment]
system命令未加壳，会导致报毒，正在修复

**Comment by RedmapleOFJvav** [comment]
您好这是已知问题 您可以截图给您的亲朋好友炫耀 本来我们不打算修复此问题
但是这个问题严重干扰用户体验 我们会尽快对该应用程序进行加壳
谢谢
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ——傻逼程序员
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 5/7/2020




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "30266-Official"<notifications@github.com&gt;; 
发送时间: 2020年5月6日(星期三) 晚上7:35
收件人: "TZG-official/Jvav-Windows"<Jvav-Windows@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [TZG-official/Jvav-Windows] &#x1F474;下载jvav报毒 (#3)





 
system命令未加壳，会导致报毒，正在修复

**Comment by RedmapleOFJvav** [comment]
您好我们正在竭力修复此问题 无奈260针对我们的项目。 您的解决方案：卸载上述应用程序并安装电脑管家、打程序员1000下。
我推荐您使用第一个傻逼的方法。十分感谢您的反馈，这是已知问题。
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ——傻逼程序员
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;5/7/2020




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "傻逼迷你世界"<notifications@github.com&gt;; 
发送时间: 2020年5月4日(星期一) 晚上8:04
收件人: "TZG-official/Jvav-Windows"<Jvav-Windows@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [TZG-official/Jvav-Windows] &#x1F474;下载jvav报毒 (#3)





 
正规编程语言怎么能被360/McAfee等杀毒软件报毒呢？说好的学习jvav不就业，全额赔么？给👴爪巴。【手动狗头】

**Comment by aliflyingfish** [comment]
我看了，这个代码没有任何毒性

**Comment by RedmapleOFJvav** [comment]
十分感谢您的反馈 代码是完全没有毒性的 请放心




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "aliflyingfish"<notifications@github.com&gt;; 
发送时间: 2020年5月15日(星期五) 中午12:18
收件人: "TZG-official/Jvav-Windows"<Jvav-Windows@noreply.github.com&gt;; 
抄送: "潮逼流子"<875648632@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [TZG-official/Jvav-Windows] &#x1F474;下载jvav报毒 (#3)





 
我看了，这个代码没有任何毒性
