### ISSUE TITLE
为什么只有迷你世界用jvav编写

### ISSUE THREAD

**Issue by du-muqiao** [TZG-official/Jvav-Windows#4]
这么好的语言应该要所有程序都用上

**Comment by RedmapleOFJvav** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"独木桥"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 下午5:12
收件人:&nbsp;"TZG-official/Jvav-Windows"<Jvav-Windows@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[TZG-official/Jvav-Windows] 为什么只有迷你世界用jvav编写 (#4)





 
这么好的语言应该要所有程序都用上

Answer{

........
