### ISSUE TITLE
可以使用在文件前加入#define的方式生成.cpp然后编译

### ISSUE THREAD

**Issue by AMIRIOX** [TZG-official/Jvav-Windows#5]
建议添加编译功能,在.jvav文件前添加#define(如#define int JVAV_INT),然后使用g++编译

jvav -compile HelloWorld.jvav

**Comment by znkzz** [comment]
这 样 就 没 有 jvav 的 特 性 了

**Comment by RedmapleOFJvav** [comment]
‘这 样 就 没 有 jvav 的 特 性 了’



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "vzpul"; 
发送时间: 2020年5月13日(星期三) 下午4:36
收件人: "TZG-official/Jvav-Windows";
抄送: "Subscribed";
主题: Re: [TZG-official/Jvav-Windows] 可以使用在文件前加入#define的方式生成.cpp然后编译 (#5)





 
这 样 就 没 有 jvav 的 特 性 了
 
&mdash;

**Comment by RedmapleOFJvav** [comment]
写一个编译器十分的困难 请持续关注jvav 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AMIRIOX"; 
发送时间: 2020年5月13日(星期三) 下午4:23
收件人: "TZG-official/Jvav-Windows";
抄送: "Subscribed";
主题: [TZG-official/Jvav-Windows] 可以使用在文件前加入#define的方式生成.cpp然后编译 (#5)





 
建议添加编译功能,在.jvav文件前添加#define(如#define int JVAV_INT),然后使用g++编译
 
jvav -compile HelloWorld.jvav
 
&mdash;
