### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by aliflyingfish** [TZG-official/Jvav-Windows#6]
我认为r.ZhangHaoyang的NB的JVAV应该添加JvavScript，这样才能体现Jvav的NB，例如读取文件里的内容，然后执行它

**Comment by RedmapleOFJvav** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"aliflyingfish"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月15日(星期五) 中午12:21
收件人:&nbsp;"TZG-official/Jvav-Windows"<Jvav-Windows@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[TZG-official/Jvav-Windows] 建议 (#6)





 
我认为r.ZhangHaoyang的NB的JVAV应该添加JvavScript，这样才能体现Jvav的NB，例如读取文件里的内容，然后执行它
