### ISSUE TITLE
瞄了一眼代码

### ISSUE THREAD

**Issue by Kamijoucen** [TZG-official/Jvav-Windows#7]
瞄了一眼代码，应该是搞了个解释器，但是看一下提交记录，几次代码风格感觉不一致，然后在代码中看到一行  
// 摘自网络 
的注释就很魔性。  怎么阿里程序员连个解释器都写不出来么。

**Comment by TheZihanGu** [comment]
这玩意不是我写的...
这项目是群里几个人开发的，扔在 Jvav.top
